version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=evolution
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  #pgadmin:
  #  image: dpage/pgadmin4:latest
  #  networks:
  #    - evolution-net
  #  environment:
  #    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #    - PGADMIN_DEFAULT_PASSWORD=admin  
  #  volumes:
  #    - pgadmin_data:/var/lib/pgadmin
  #  ports:
  #    - 4000:80
  #  links:
  #    - postgres
  
  #redis:
  #  image: redis:latest
  #  networks:
  #    - evolution-net
  #  container_name: redis
  #  command: >
  #    redis-server --port 6379 --appendonly yes
  #  volumes:
  #    - evolution_redis:/data
  #  ports:
  #    - 6379:6379

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    networks:
      - evolution-net
    environment:
      - RABBITMQ_ERLANG_COOKIE=33H2CdkzF5WrnJ4ud6nkUdRTKXvbCHeFjvVL71p
      - RABBITMQ_DEFAULT_VHOST=default
      - RABBITMQ_DEFAULT_USER=USER
      - RABBITMQ_DEFAULT_PASS=PASSWORD
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672

  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:v2.3.4
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
       - rabbitmq 
       - postgres
    #  - redis
    networks:
      - evolution-net
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  postgres_data:
  #pgadmin_data:
  #evolution_redis:
  rabbitmq_data:
  evolution_instances:


networks:
  evolution-net:
    name: evolution-net
    driver: bridge